// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("EdIlyin.FSharp.Boxcar")>]
[<assembly: AssemblyProductAttribute("EdIlyin.FSharp.Boxcar")>]
[<assembly: AssemblyDescriptionAttribute("Combines Result and Job")>]
[<assembly: AssemblyVersionAttribute("0.0.3")>]
[<assembly: AssemblyFileVersionAttribute("0.0.3")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "EdIlyin.FSharp.Boxcar"
    let [<Literal>] AssemblyProduct = "EdIlyin.FSharp.Boxcar"
    let [<Literal>] AssemblyDescription = "Combines Result and Job"
    let [<Literal>] AssemblyVersion = "0.0.3"
    let [<Literal>] AssemblyFileVersion = "0.0.3"
    let [<Literal>] AssemblyConfiguration = "Release"
